In [1]:
import numpy as np

In [4]:
A = np.array([
    [5,2,0],
    [2,5,0],
    [-3,4,6]
])

In [16]:
U[0].normalize

AttributeError: 'numpy.ndarray' object has no attribute 'normalize'

In [23]:
UT = np.array([
    [0, 0, 1],
    [3, -3, 7],
    [1, 1, 1]
])

U = UT.transpose()
U

array([[ 0,  3,  1],
       [ 0, -3,  1],
       [ 1,  7,  1]])

In [25]:
c0 = np.linalg.norm(U[0])
c1 = np.linalg.norm(U[1])
c2 = np.linalg.norm(U[2])

C = [c0,c1,c2]

In [26]:
Un = [0,0,0]
for i in range(len(U)):
    Un[i] = U[i] * 1/C[i]
Un = np.array(Un)

In [43]:
Un @ Un.transpose()

array([[ 1.        , -0.8       ,  0.97417637],
       [-0.8       ,  1.        , -0.88561489],
       [ 0.97417637, -0.88561489,  1.        ]])

In [31]:
Un
UnT = Un.transpose()

In [9]:
lambdas = np.array([
    [6,0,0],
    [0,3,0],
    [0,0,7]
])

In [35]:
Un @ lambdas @ UnT

array([[ 3.4       , -2.        ,  3.0996521 ],
       [-2.        ,  3.4       , -2.47972168],
       [ 3.0996521 , -2.47972168,  3.1372549 ]])

In [39]:
Un @ UnT

array([[ 1.        , -0.8       ,  0.97417637],
       [-0.8       ,  1.        , -0.88561489],
       [ 0.97417637, -0.88561489,  1.        ]])

intento 2 para diagonalzar

In [45]:
A = np.array([
    [5,2,0],
    [2,5,0],
    [-3,4,6]
])

Lamb, EVecs = np.linalg.eig(A)